using UnityEditor;
using UnityEngine;

namespace LeonAkasaka.UnionAir.Editor
{
    /// <summary>
    /// Who owns an AnimationClip's settings, and what a write to one that belongs to an
    /// importer must answer.
    ///
    /// A clip inside an `.fbx` is not an asset a client can write. Its settings live on the
    /// <see cref="ModelImporter"/> that produced it, and
    /// <c>AnimationUtility.SetAnimationClipSettings</c> mutates an in-memory object the
    /// next reimport discards. That is a silent data-loss path: the request answers 200,
    /// the Inspector shows the change, and it is gone the next time anything touches the
    /// model.
    ///
    /// Imported clips are the ordinary case rather than an edge one -- a character's
    /// animation set usually arrives as `.fbx` -- so the boundary has to be visible in the
    /// read and enforced on every write.
    /// </summary>
    internal static class AnimationClipOwnership
    {
        /// <summary>
        /// Whether the clip at this path belongs to an importer.
        ///
        /// Decided by asking the AssetDatabase what imported the path, not by looking at
        /// the extension: the set of model extensions is Unity's to extend, and a project
        /// can add importers for its own.
        /// </summary>
        internal static bool IsImported(string assetPath, out string importerType)
        {
            importerType = null;
            var importer = AssetImporter.GetAtPath(assetPath);
            if (importer == null) return false;

            // A `.anim` file is imported too -- by NativeFormatImporter, which does not own
            // the clip's settings, it just reads the file the clip is stored in. What makes
            // a clip unwritable is an importer that generates it.
            if (importer is ModelImporter)
            {
                importerType = nameof(ModelImporter);
                return true;
            }

            return false;
        }

        internal static string RefusalMessage(string assetPath, string importerType)
            => $"This clip is generated by {importerType} from '{assetPath}', which owns its settings. " +
               "A write here would change an in-memory object that the next reimport discards. " +
               "Change the importer instead, through PATCH /api/assets/model-importer/{guid}, " +
               "where the clip's definition is settings.clips.";

        /// <summary>
        /// Answers the request when the clip is owned by an importer.
        ///
        /// 409 rather than 400: the request is well formed, and the same body against a
        /// `.anim` clip would succeed. What refuses it is the asset, not the syntax.
        /// </summary>
        internal static bool RefuseIfImported(string assetPath, UnionAirResponse response)
        {
            if (!IsImported(assetPath, out var importerType)) return false;

            var sb = new System.Text.StringBuilder();
            sb.Append("{\"error\":").Append(RestResponse.FormatNullableString(
                RefusalMessage(assetPath, importerType)));
            sb.Append(",\"assetPath\":").Append(RestResponse.FormatNullableString(assetPath));
            sb.Append(",\"importer\":").Append(RestResponse.FormatNullableString(importerType));
            sb.Append(",\"writable\":false}");
            RestResponse.Send(response, sb.ToString(), 409);
            return true;
        }

        /// <summary>
        /// How many AnimationClips share this path, and what they are called.
        ///
        /// <c>LoadAssetAtPath</c> returns whichever the importer lists first, so an FBX
        /// holding several takes exposes one of them by GUID and hides the rest. Addressing
        /// an individual one is a sub-asset problem this endpoint does not solve; reporting
        /// that the others exist is the least it can do instead of presenting one clip as
        /// though it were the path's whole content.
        /// </summary>
        internal static string[] ClipNamesAt(string assetPath)
        {
            var names = new System.Collections.Generic.List<string>();
            foreach (var asset in AssetDatabase.LoadAllAssetsAtPath(assetPath))
            {
                var clip = asset as AnimationClip;
                if (clip != null) names.Add(clip.name);
            }
            return names.ToArray();
        }
    }
}
